"""initial schema

Revision ID: 0f3a8256f33b
Revises: 
Create Date: 2026-08-27 12:51:59.216995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f3a8256f33b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('image_filename', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('company_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('tax_id', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('fax', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('bank_account', sa.String(length=200), nullable=True),
    sa.Column('contact_person', sa.String(length=50), nullable=True),
    sa.Column('closing_day', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixed_expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('p_products', sa.Boolean(), nullable=True),
    sa.Column('p_vendors', sa.Boolean(), nullable=True),
    sa.Column('p_customers', sa.Boolean(), nullable=True),
    sa.Column('p_sales', sa.Boolean(), nullable=True),
    sa.Column('p_purchases', sa.Boolean(), nullable=True),
    sa.Column('p_employees', sa.Boolean(), nullable=True),
    sa.Column('p_finance', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('shopee_shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('platform_shop_id', sa.String(length=30), nullable=False),
    sa.Column('api_key', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('platform_shop_id')
    )
    op.create_table('unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_no', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('tax_id', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('fax', sa.String(length=20), nullable=True),
    sa.Column('contact_person', sa.String(length=50), nullable=True),
    sa.Column('bank_account', sa.String(length=100), nullable=True),
    sa.Column('warehouse_address', sa.String(length=200), nullable=True),
    sa.Column('closing_day', sa.Integer(), nullable=True),
    sa.Column('payment_day', sa.Integer(), nullable=True),
    sa.Column('t1_amt', sa.Float(), nullable=True),
    sa.Column('t1_dis', sa.Float(), nullable=True),
    sa.Column('t2_amt', sa.Float(), nullable=True),
    sa.Column('t2_dis', sa.Float(), nullable=True),
    sa.Column('t3_amt', sa.Float(), nullable=True),
    sa.Column('t3_dis', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_no')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code1', sa.String(length=50), nullable=True),
    sa.Column('code2', sa.String(length=50), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('safety_stock', sa.Integer(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('shopee_item_id', sa.String(length=50), nullable=True),
    sa.Column('shopee_model_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_shopee_item_id'), ['shopee_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_shopee_model_id'), ['shopee_model_id'], unique=False)

    op.create_table('purchase_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('billing_year', sa.Integer(), nullable=True),
    sa.Column('billing_month', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_table('purchase_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('req_no', sa.String(length=50), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('billing_year', sa.Integer(), nullable=True),
    sa.Column('billing_month', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('req_no')
    )
    op.create_table('purchase_return_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('billing_year', sa.Integer(), nullable=False),
    sa.Column('billing_month', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('total_return_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_table('shopee_order_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('order_sn', sa.String(length=50), nullable=False),
    sa.Column('package_number', sa.String(length=50), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shopee_shop.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'order_sn', name='uq_shopee_order_raw_shop_order')
    )
    with op.batch_alter_table('shopee_order_raw', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shopee_order_raw_order_sn'), ['order_sn'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vendor_payment_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('billing_year', sa.Integer(), nullable=True),
    sa.Column('billing_month', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cust_no', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('tax_id', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('fax', sa.String(length=20), nullable=True),
    sa.Column('contact_person', sa.String(length=50), nullable=True),
    sa.Column('bank_account', sa.String(length=100), nullable=True),
    sa.Column('shipping_address', sa.String(length=200), nullable=True),
    sa.Column('invoice_address', sa.String(length=200), nullable=True),
    sa.Column('closing_day', sa.Integer(), nullable=True),
    sa.Column('payment_day', sa.Integer(), nullable=True),
    sa.Column('price_discount', sa.Float(), nullable=True),
    sa.Column('post_discount', sa.Float(), nullable=True),
    sa.Column('has_invoice', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cust_no')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emp_no', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('emp_no')
    )
    op.create_table('purchase_order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_request_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['purchase_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_return_order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_return_order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drop_ship_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('billing_year', sa.Integer(), nullable=True),
    sa.Column('billing_month', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_table('invoice_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('billing_year', sa.Integer(), nullable=True),
    sa.Column('billing_month', sa.Integer(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('is_printed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('billing_year', sa.Integer(), nullable=True),
    sa.Column('billing_month', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('picking_slip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slip_no', sa.String(length=50), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slip_no')
    )
    op.create_table('return_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('billing_year', sa.Integer(), nullable=True),
    sa.Column('billing_month', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('total_return_amount', sa.Float(), nullable=True),
    sa.Column('total_cost_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_table('sales_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('billing_year', sa.Integer(), nullable=True),
    sa.Column('billing_month', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('gross_profit', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('shopee_order_sn', sa.String(length=50), nullable=True),
    sa.Column('shopee_package_number', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shopee_shop.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    with op.batch_alter_table('sales_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_order_shopee_order_sn'), ['shopee_order_sn'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_order_shopee_package_number'), ['shopee_package_number'], unique=False)

    op.create_table('drop_ship_order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['drop_ship_order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('picking_slip_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slip_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['slip_id'], ['picking_slip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('return_order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['return_order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['sales_order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_order_item')
    op.drop_table('return_order_item')
    op.drop_table('picking_slip_item')
    op.drop_table('drop_ship_order_item')
    with op.batch_alter_table('sales_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_order_shopee_package_number'))
        batch_op.drop_index(batch_op.f('ix_sales_order_shopee_order_sn'))

    op.drop_table('sales_order')
    op.drop_table('return_order')
    op.drop_table('picking_slip')
    op.drop_table('payment_record')
    op.drop_table('invoice_record')
    op.drop_table('drop_ship_order')
    op.drop_table('purchase_return_order_item')
    op.drop_table('purchase_request_item')
    op.drop_table('purchase_order_item')
    op.drop_table('employee')
    op.drop_table('customer')
    op.drop_table('vendor_payment_record')
    op.drop_table('user')
    with op.batch_alter_table('shopee_order_raw', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shopee_order_raw_order_sn'))

    op.drop_table('shopee_order_raw')
    op.drop_table('purchase_return_order')
    op.drop_table('purchase_request')
    op.drop_table('purchase_order')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_shopee_model_id'))
        batch_op.drop_index(batch_op.f('ix_product_shopee_item_id'))

    op.drop_table('product')
    op.drop_table('vendor')
    op.drop_table('unit')
    op.drop_table('shopee_shop')
    op.drop_table('role')
    op.drop_table('fixed_expense')
    op.drop_table('company_profile')
    op.drop_table('category')
    op.drop_table('announcement')
    # ### end Alembic commands ###
