"""add ShopeeProductMapping for multi-shop item/model mapping

Revision ID: d0b3c7d03782
Revises: 0f3a8256f33b
Create Date: 2026-09-09 10:26:05.926765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0b3c7d03782'
down_revision = '0f3a8256f33b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopee_product_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('platform_item_id', sa.String(length=50), nullable=False),
    sa.Column('platform_model_id', sa.String(length=50), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('allocation_ratio', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shopee_shop.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'platform_item_id', 'platform_model_id', name='uq_shopee_mapping_shop_item_model')
    )
    with op.batch_alter_table('shopee_product_mapping', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shopee_product_mapping_platform_item_id'), ['platform_item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopee_product_mapping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shopee_product_mapping_platform_item_id'))

    op.drop_table('shopee_product_mapping')
    # ### end Alembic commands ###
